### ISSUE TITLE
strain isotypes not accessible when package is loaded

### ISSUE THREAD

**Issue by Thatguy027** [AndersenLab/cegwas#13]
``` r
>devtools::install_github("AndersenLab/cegwas")
>library(cegwas)

>strain_isotype

Error: object 'strain_isotype' not found
```

i don't think the `strain_isotype` file was loaded into the package correctly. as far as i know, all data associated with the package should be accessible by user for it to work in the functions.when i load sysdata.Rda, `strain_isotype` is present, so i am not sure why i can't call the data. is there a way to load data that is accessible by functions but not by user?  

also, update the datasets.R script with any new data sets that are added to the package.

**Comment by Thatguy027** [comment]
ah, `internal = TRUE`

**Comment by danielecook** [comment]
I am slowly learning all the ins and outs. You can keep certain datasets
private within a package. Because that's just a vector I didn't think it
needed to be made available easily.

Dan

**Comment by danielecook** [comment]
I will make the strain_isotype_warnings datafile available soon.

**Comment by danielecook** [comment]
This is accessible now.
