### ISSUE TITLE
Handling of P-values

### ISSUE THREAD

**Issue by danielecook** [AndersenLab/cegwas#16]
I would like to suggest that the `gwas_mappings` function and `process_mappings` function return all p-values regardless of significance. What is the rational behind throwing an error if no significant peaks are found? I think this is something that should be processed by the user outside of the `gwas_mappings` and `process_mappings` function as some people may want to see suggestive signals or negative results and this is not possible currently. I nominate Stefan! But happy to discuss.

**Comment by synmuv** [comment]
I agree. It would be great to plot the output from a mapping even if nothing mapped.

**Comment by danielecook** [comment]
I'm implementing this on a developmental branch

**Comment by danielecook** [comment]
[This diff addresses this issue](https://github.com/AndersenLab/cegwas/compare/devel?diff=unified&expand=1&name=devel). Let me know if it is okay to merge into the master branch. Thanks!

**Comment by Thatguy027** [comment]
as far as i know this issue was already taken care of days ago. in gwas_mappings set only_sig == FALSE. in process_mappings set BF to whatever suggestive p-value you like. maybe i am missing something about what you are asking, let's discuss tomorrow before major merge.

**Comment by danielecook** [comment]
Basically, the issue is that this error is thrown if you use `only_sig == F` and **do not** lower the bonferroni on trait data with no significant peaks:

```
Error in process_mappings(mapping_df, phenotype_df = processed_phenotypes,  : 
  No significant peaks identified. Try using a custom BF with the process_mappings() function.
```

You can lower bonferroni by decreasing `BF` - however this results in a bunch of peaks showing up:

<img width="1124" alt="screen shot 2015-10-02 at 12 58 14 am" src="https://cloud.githubusercontent.com/assets/1536935/10240408/2c56e6a0-68a1-11e5-81a6-89b068f904f7.png">

Essentially what this boils down to is that this setup makes it impossible to see what the plot looks like at the appropriate bonferroni level without drawing the peaks everywhere.

**Comment by danielecook** [comment]
I've committed my changes - please update when you can.
