### ISSUE TITLE
Tried to update isotype file to no avail

### ISSUE THREAD

**Issue by synmuv** [AndersenLab/cegwas#17]
I tried to add some published missing isotypes, but the change didn't take. What is the deal with formatting? I tried tab-delimited. 

We need to incorporate published isotopes from Rockman et al. PLoS Genetics, McGrath et al. Neuron, and Andersen et al. Nature Genetics. Also, we should not include N2 clones (like TR403). Many of those strains are actually recombinants. See McGrath et al.

**Comment by danielecook** [comment]
The tsv will be build now automatically when installing.
