### ISSUE TITLE
JU360 and JU363 not recognized as isotype

### ISSUE THREAD

**Issue by synmuv** [AndersenLab/cegwas#18]
I ran the recent updates. The groupings worked well, but the mapping algorithm output an error for an unknown isotype for JU363/JU360.

**Comment by danielecook** [comment]
The current isotype dataframe includes JU360 and JU363 strains and isotype (JU360). Did you install the latest version?

**Comment by synmuv** [comment]
Yes. I did. The error came from the mapping function. If you run the data.frame I sent before, you should see the same result.

**Comment by danielecook** [comment]
The reason this is happening is that strain `JU362` is assigned an isotype of `JU363`. We consider the iso-strain (the isotype name namesake) to be`JU360`.

**Comment by danielecook** [comment]
I have updated the strain-isotype file to change the `JU362` isotype from `JU363` to `JU360`; We can alter this though.

**Comment by synmuv** [comment]
That sounds like a good reason. Let's keep it with JU360. Thanks!
