### ISSUE TITLE
Add support for inputting data in long format

### ISSUE THREAD

**Issue by danielecook** [AndersenLab/cegwas#2]
I'm having a tough time getting the data into the wide format (transposed). For example:

| Sample | Telomere_LENGTH | telomere_resids |
| :-- | --: | --: |
| AB1 | 95.4394 | -8.0219629 |
| AB4 | 163.0770 | 52.6676733 |
| CB4851_CGC | 112.4590 | -1.5121948 |
| CB4852 | 82.3885 | -27.1877090 |
| CB4853 | 86.8552 | -17.6663792 |
| CB4854 | 114.3230 | -2.5027189 |

To me - this seems like the more intuitive and straightforward format to begin with. 

Ideally, maybe it would be capable of reading both? 

**Update** Got it to work with this code:

Maybe it can be adapted for the function. I might look into if I have time too.

``` r
phenotypes <- read_tsv("../data/genomic_traits.txt")
colset <- phenotypes[,1]$Sample
trait_names <- colnames(phenotypes)[2:3]
phenotypes <- as.data.frame(t(phenotypes[,2:3]))
names(phenotypes) <- colset
phenotypes <- mutate(phenotypes, trait = trait_names) %>%
  select(trait, everything())
```

**Comment by Thatguy027** [comment]
tidyr::spread

makes long into wide.

 i wanted to avoid having multiple inputs, but maybe i can incorporate a long formatted input.

**Comment by danielecook** [comment]
I added this.
