### ISSUE TITLE
snpeff does not take gene names as inputs

### ISSUE THREAD

**Issue by synmuv** [AndersenLab/cegwas#20]
It appears that snpeff will take three or four-letter gene names (or WBG names) but will not take cosmid/YAC gene names. Because most gene names in C. elegans are cosmid/YAC gene names, we have two options going forward: (1) provide a function that will connect cosmid/YAC gene names and three- or four-letter gene names to WBG names or (2) add the ability to query snpeff with cosmid/YAC gene names. Thoughts?

The error I get is:

snpeff("F37A4.8")
Looking up F37A4.8 () position
Error in httr::content(wb_ret)$location : 
  object of type 'externalptr' is not subsettable

**Comment by danielecook** [comment]
We can resolve this by pulling gene names from the gff from wormbase I believe. This would extend functionality to other classes of genomic features (e.g. ncRNA) - which would be useful for lots of things.

**Comment by synmuv** [comment]
Do you mean the cosmid/YAC gene names? These names should be a preferred entry because they are more recognizable than the WBG. I guess it would be good to have the input be any of the three gene name types. Right?

**Comment by danielecook** [comment]
This is resolved - all of these should work. Doesn't work for introns/exons yet. Still need to add ability to query by type (e.g. piRNA).

`snpeff(c("pot-2", "F57C2.3", "WBGene00010195", "II:14524173-14525111"))`
