### ISSUE TITLE
snpeff error

### ISSUE THREAD

**Issue by synmuv** [AndersenLab/cegwas#21]
The new function seems to recognize the three different gene name types, but I get the following error:

Query: isw-1; region - III:6703993-6710055
sh: bcftools: command not found
Querying isw-1 remotely
sh: bcftools: command not found
Error in snpeff("isw-1", severity = "HIGH") : No Results

**Comment by danielecook** [comment]
You don't have bcftools installed. Install with `brew install samtools`; I'll write a chunk of code to ensure that bcftools is installed.
