### ISSUE TITLE
snpeff still not working

### ISSUE THREAD

**Issue by synmuv** [AndersenLab/cegwas#22]
New error:

[main] Unrecognized command.
Error in snpeff(unique(g.list$Gene.name)[-1], severity = "HIGH") : 
  bcftools 1.2+ required for this function

Seems like you need the newest bcftools to run snpeff. Please make sure that it gets installed.

**Comment by danielecook** [comment]
You can update bcftools with:

```
brew update
brew install samtools --upgrade
```

It's a little unorthodox to have an R package manage command line tools (by upgrading/installing). We can discuss. If this is platform independent than it also makes it a challenge to write code to do so (e.g. writing installation instructions for mac/linux/windows/etc.)

**Comment by synmuv** [comment]
I'm still having problems. The brew update could tap homebrew-science. We can look it over when I get back. 

In terms of requirements, I agree. We'll have to make an extensive readme to make sure users have the correct software install to use the package.

**Comment by danielecook** [comment]
I've (hopefully) resolved any issues with the snpeff function. I made the
following changes:

1.) missing identifiers are bypassed
2.) warning messages from index files are no longer output.
3.) Genes/regions/etc. can be specified without wrapping as a vector. e.g. :
snpeff("pot-1", "pot-2", "pot-3"); vectors can also be used. Specifying
severity/etc. must be done so by using the parameter name.

Let me know if you run into any issues.

Dan

**Comment by synmuv** [comment]
Michael and I are still having issues getting snpeff to work on specific computers. My home computer still has the "bcftools 1.2+ required for this function" error. Same goes for Michael and the fix above doesn't work. Let's discuss how to solve it.

**Comment by danielecook** [comment]
This is not an issue with the snpeff function. It is a result of bcftools not being appropriately installed.
