### ISSUE TITLE
Gene query with internal genes

### ISSUE THREAD

**Issue by synmuv** [AndersenLab/cegwas#23]
snpeff("hrg-1") returns variants for hrg-1 and a gene internal to hrg-1 called mop-25.1. I manually added a check to keep variants where the query and the gene_name match, but it only works for variants with gene_name designations (i.e. not most genes).

**Comment by danielecook** [comment]
Okay! With the latest update cegwas (880445b0ab11273ecbe36f10e725b71919d793a2) this should be resolved. However, I had to add a database to take care of this. The database is rather large (227 Mb) - so we'll have to host and distribute it ourselves. You only download it once (unless we update genome builds; Currently we are on WS245). When installing, R will check whether you have it and download it if not.

**One issue** if genes are overlapping on opposite strands this might still return variants.  What are your thoughts on that? Should we eliminate those as well?

### Filtering on exons

The default is to filter on exons only. You can expand a query using something like this:

`snpeff("pot-2", severity = "ALL", elements = c("intron","exon"))`

### The Database

Once you've installed an updated version of cegwas, you can use the following code to access the underlying database:
`elegans_gff <- dplyr::tbl(dplyr::src_sqlite(paste0("~/.WS", wb_build, ".elegans_gff.db")), "feature_set")`

The database itself is pretty useful in that we can probably use it to sketch out gene models beneath fine mapping plots or in other contexts. It provides all of the gene elements (CDS, introns, exons, UTRs) in addition to locations of all the piRNAs, rRNAs etc.
