### ISSUE TITLE
Crashing is caused by parallel

### ISSUE THREAD

**Issue by danielecook** [AndersenLab/cegwas#4]
I've isolated the reason for mapping failing (and Rstudio crashing) - it occurs at the point of parallel being run. Setting `cores = 1` within the GWAS function resolves the issue.

I am using parallel version `3.2.2`

**Comment by danielecook** [comment]
Appears to be resolved...will test tomorrow.

**Comment by danielecook** [comment]
One issue - parallel execution doesn't appear to work unless you load foreach using `library(foreach)` OUTSIDE of the cegwas_map or gwas_mappings function. Not sure why; error is `%dopar% not found`.

**Comment by Thatguy027** [comment]
this all fixed?
